import { defineConfig } from 'tsup';

export default defineConfig({
  entry: [
    'src/index.ts',
    'src/index.native.ts',
    'src/primitives/index.web.tsx',
    'src/primitives/index.native.tsx',
    'src/layout/index.web.tsx',
    'src/layout/index.native.tsx',
    'src/components/index.web.tsx',
    'src/components/index.native.tsx',
    'src/theme/index.ts',
    'src/icons/index.web.tsx',
    'src/icons/index.native.tsx',
    'src/hooks/index.web.ts',
    'src/hooks/index.native.ts',
  ],
  format: ['cjs', 'esm'],
  dts: true,
  splitting: false,
  sourcemap: true,
  clean: true,
  outDir: 'dist',
  external: [
    'react',
    'react-dom',
    'react-native',
    'react-native-web',
    'lucide-react',
    'lucide-react-native',
    '@radix-ui/react-label',
    '@radix-ui/react-progress',
    '@radix-ui/react-slot',
    '@radix-ui/react-checkbox',
    '@radix-ui/react-switch',
    '@radix-ui/react-select',
    '@radix-ui/react-tabs',
    '@radix-ui/react-radio-group',
    '@radix-ui/react-slider',
    '@radix-ui/react-dialog',
    '@radix-ui/react-alert-dialog',
    '@radix-ui/react-popover',
    '@radix-ui/react-tooltip',
    '@radix-ui/react-dropdown-menu',
    '@radix-ui/react-scroll-area',
    '@radix-ui/react-collapsible',
    '@radix-ui/react-accordion',
    'vaul',
    'cmdk',
    'react-hook-form',
    'react-day-picker',
    'date-fns',
    '@radix-ui/react-avatar',
    'recharts',
    '@radix-ui/react-aspect-ratio',
    '@radix-ui/react-context-menu',
    '@radix-ui/react-direction',
    '@radix-ui/react-hover-card',
    '@radix-ui/react-menubar',
    '@radix-ui/react-navigation-menu',
    '@radix-ui/react-toast',
    '@radix-ui/react-toggle',
    '@radix-ui/react-toggle-group',
    'embla-carousel',
    'embla-carousel-react',
    '@tanstack/react-table',
    'react-resizable-panels',
    'sonner',
  ],
});
