export const tokens = {
  radius: {
    sm: 6,
    md: 8,
    lg: 10,
    xl: 14,
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
    xxl: 32,
  },
  typography: {
    sizes: {
      xs: 12,
      sm: 14,
      md: 16,
      lg: 18,
      xl: 20,
      xxl: 24,
    },
    weights: {
      regular: 400,
      medium: 500,
      semibold: 600,
      bold: 700,
      extrabold: 800,
    },
  },
  colors: {
    light: {
      background: 'oklch(0.985 0 0)',
      foreground: 'oklch(0.145 0 0)',
      card: 'oklch(1 0 0)',
      cardForeground: 'oklch(0.145 0 0)',
      primary: 'oklch(0.58 0.233 255)',
      primaryForeground: 'oklch(1 0 0)',
      secondary: 'oklch(0.97 0 0)',
      secondaryForeground: 'oklch(0.205 0 0)',
      destructive: 'oklch(0.577 0.245 27.325)',
      border: 'oklch(0.922 0 0)',
      input: 'oklch(0.922 0 0)',
      muted: 'oklch(0.97 0 0)',
      mutedForeground: 'oklch(0.556 0 0)',
      ring: 'oklch(0.58 0.233 255)',
    },
    dark: {
      background: 'oklch(0.1 0 0)',
      foreground: 'oklch(0.985 0 0)',
      card: 'oklch(0.14 0 0)',
      cardForeground: 'oklch(0.985 0 0)',
      primary: 'oklch(0.58 0.233 255)',
      primaryForeground: 'oklch(0.985 0 0)',
      secondary: 'oklch(0.269 0 0)',
      secondaryForeground: 'oklch(0.985 0 0)',
      destructive: 'oklch(0.704 0.191 22.216)',
      border: 'oklch(1 0 0 / 10%)',
      input: 'oklch(1 0 0 / 15%)',
      muted: 'oklch(0.269 0 0)',
      mutedForeground: 'oklch(0.708 0 0)',
      ring: 'oklch(0.58 0.233 255)',
    },
  },
  elevation: {
    none: 0,
    sm: 1,
    md: 3,
    lg: 8,
  },
  zIndex: {
    base: 0,
    dropdown: 100,
    modal: 200,
    toast: 300,
  },
} as const;

export type UITokens = typeof tokens;

export const nativewindTokenMap = {
  colors: {
    background: tokens.colors.light.background,
    foreground: tokens.colors.light.foreground,
    card: tokens.colors.light.card,
    cardForeground: tokens.colors.light.cardForeground,
    primary: tokens.colors.light.primary,
    primaryForeground: tokens.colors.light.primaryForeground,
    secondary: tokens.colors.light.secondary,
    secondaryForeground: tokens.colors.light.secondaryForeground,
    destructive: tokens.colors.light.destructive,
    border: tokens.colors.light.border,
    input: tokens.colors.light.input,
    muted: tokens.colors.light.muted,
    mutedForeground: tokens.colors.light.mutedForeground,
    ring: tokens.colors.light.ring,
  },
  borderRadius: {
    sm: tokens.radius.sm,
    md: tokens.radius.md,
    lg: tokens.radius.lg,
    xl: tokens.radius.xl,
  },
  spacing: tokens.spacing,
};
